//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalPagos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosFiscales
    {
        public int Id_DatFis { get; set; }
        public int id_cliente { get; set; }
        public string nombre { get; set; }
        public string rfc { get; set; }
        public string uso_cfdi { get; set; }
        public string regimen_fiscal { get; set; }
        public string direccion { get; set; }
        public string colonia { get; set; }
        public string pais { get; set; }
        public string estado { get; set; }
        public string codigo_postal { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    }
}
