//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalPagos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StripeCustomer
    {
        public int id_stcust { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public string stripe_idcliente { get; set; }
    }
}
